defaults:
  - base

experiment:
  name: "srcnn_x2"

data:
  scale: 2
  patch_size: 32
  batch_size: 128

model:
  name: "srcnn"
  scale: 2
  in_channels: 1       # Y-channel only (standard for SRCNN)
  out_channels: 1
  num_channels: [64, 32]
  kernel_sizes: [9, 1, 5]

trainer:
  max_epochs: 200
  grad_accumulation_steps: 1

optimizer:
  type: "Adam"
  lr: 1.0e-4
